- name: Deploy Calculator Container Using Docker CLI
  hosts: localhost
  remote_user: girish
  become: yes
  tasks:
    - name: Pull the latest Docker image from Docker Hub
      shell: docker pull girish445g/sc-calculator
      register: pull_result
      changed_when: "'Downloaded newer image' in pull_result.stdout or 'Pull complete' in pull_result.stdout"

    - name: Display Pull Result
      debug:
        var: pull_result.stdout

    - name: Stop and remove any existing container with the same name
      shell: |
        docker stop sc-calculator || true
        docker rm sc-calculator || true
      ignore_errors: yes

    - name: Run the Docker container
      shell: docker run -it -d --name sc-calculator girish445g/sc-calculator
      register: run_result
      changed_when: "'Error' not in run_result.stderr"

    - name: Display Container Run Result
      debug:
        var: run_result.stdout
